src/Components/Searchbar.js, src/Navigators/Main.js, src/Screens/Browse/Browse.js, src/Screens/Browse/GlobalSearch.js, src/Screens/Browse/components/GlobalSearchNovelCover.js, src/Screens/Browse/components/GlobalSearchNovelList.js, src/Screens/Novel/Novel.js
=> Add global search

src/sources/jp/syosetu.js, src/sources/sources.js
Oneshots didn't work at all because of use of scaner from lnreader-sources
Oneshots now load properly desciptions (I chaged code a bit because it looked gross to do it in a one-liner)
Syosetsu changed into Syosetu as it should be
=> Fixed Syosetu name and Oneshot not working

package.json
=> format: Prettier settings in package.json

src/screens/Browse/BrowseSettings.js, src/sources/sources.json
Small nitpick in the language name
=> fix: Indonesia -> Indonesian

src/sources/en/reaperscans.js, src/sources/sources.js, src/sources/sources.json
Closes LNReader/lnreader-sources#49
The script was similar to boxnovel except the searchScrape and some minor stuff in other scrapers.
=> feat(sources): Add ReaperScans Novels

README.md
Add some badges 
Also should we remove the LICENSE and Downloads section at the bottom?
=> docs(readme): Add badges

src/screens/Novel/components/ChapterItem.js
When a chapter was bookmarked the list wasn't updating
=> fix(chapterlist): Bookmark not updating when added

android/app/src/main/AndroidManifest.xml
```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 4000012 byte allocation with 1815584 free bytes and 1773KB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
at android.graphics.Bitmap.nativeCreate(Bitmap.java)
at android.graphics.Bitmap.createBitmap(Bitmap.java:859)
at android.graphics.Bitmap.createBitmap(Bitmap.java:829)
at android.graphics.Bitmap.createBitmap(Bitmap.java:796)
at com.facebook.imagepipeline.memory.BucketsBitmapPool.alloc(BucketsBitmapPool.java:54)
at com.facebook.imagepipeline.memory.BucketsBitmapPool.alloc(BucketsBitmapPool.java:29)
at com.facebook.imagepipeline.memory.BasePool.get(BasePool.java:266)
at com.facebook.imagepipeline.platform.DefaultDecoder.decodeFromStream(DefaultDecoder.java:217)
at …
```
=> java.lang.OutOfMemoryError

package-lock.json, package.json, src/hooks/githubUpdateChecker.js, src/navigators/Main.js, src/screens/more/About.js, src/utils/utils.js
Now you can manage the version through one file.
=> Utils for version

package-lock.json, package.json, src/navigators/Main.js, src/screens/reader/ReaderScreen.js
https://github.com/LNReader/lnreader/issues/121
=> Keep Screen On

src/sources/multisrc/madara/MadaraGenerator.js, src/sources/sourceManager.ts, src/sources/sources.json
=> TeamXNovel New Source

src/sources/ru/renovels.js, src/sources/sourceManager.ts, src/sources/sources.json
=> A new source of Renovels

src/sources/ru/jaomix.js, src/sources/ru/ranobelib.js, src/sources/ru/ranoberf.js, src/sources/ru/renovels.js, src/sources/ru/rulate.js, src/sources/sourceManager.ts, src/sources/sources.json
New sources added: 
- Jaomix (Closes LNReader/lnreader-sources#203)
- Rulate (Closes LNReader/lnreader-sources#76)
- РанобэРФ
=> new sources added

src/sources/ru/jaomix.js, src/sources/ru/ranobehub.js, src/sources/ru/ranobelib.js, src/sources/ru/ranoberf.js, src/sources/ru/renovels.js, src/sources/ru/rulate.js
In the sources renovels, ranobelib, ranoberf, jaomix, ranobehub, rulate will now display tags, author, status, etc.
=> source update

src/sources/ru/ranoberf.js, src/sources/ru/renovels.js, src/sources/ru/rulate.js
Change in renovels
- corrected duplication of novels
- improved cover quality
Changes in rulate
- added authentication bypass for some light novels
=> Source corrected

src/screens/reader/ReaderScreen.js, src/screens/reader/components/WebViewReader.js
Now webview has webViewScroll which after any change scrolls webView to given percentage
=> feat(webview-scroll): webview scrolls to saved

package.json, src/screens/novel/components/Info/NovelInfoHeader.js
=> fix(clipboard): Fixed clipboard dependency

android/app/src/main/java/com/rajarsheechatterjee/LNReader/MainActivity.java, android/app/src/main/java/com/rajarsheechatterjee/LNReader/MainApplication.java, android/app/src/main/java/com/rajarsheechatterjee/VolumeButtonListener/VolumeButtonListener.java, android/app/src/main/java/com/rajarsheechatterjee/VolumeButtonListener/VolumeButtonListenerPackage.java, src/redux/settings/settings.reducer.js, src/screens/reader/ReaderScreen.js, src/screens/reader/components/ReaderBottomSheet/ReaderBottomSheet.tsx, src/screens/reader/components/WebViewReader.tsx, src/screens/settings/SettingsReaderScreen/SettingsReaderScreen.tsx, src/utils/volumeButtonListener.ts
Partially finishes #123 (need to implement it into normal reader too)
=> feat(volume-scroll): Added option to scroll WebView using volume buttons

src/screens/history/components/HistoryCard/HistoryCard.tsx, src/screens/reader/components/BottomInfoBar/BottomInfoBar.tsx, src/sources/helpers/parseDate.js, src/sources/multisrc/madara/MadaraScraper.js, strings/translations.ts
Synchronizes the moment language
=> moment sync

src/sources/en/noveltop1.js, src/sources/ru/ranobehub.js, src/sources/ru/ranobelib.js, src/sources/ru/ranoberf.js, src/sources/ru/renovels.js, src/sources/ru/rulate.js, src/sources/sourceManager.ts, src/sources/sources.json, src/utils/constants/dateFormats.ts
NovelTop1 (Closes LNReader/lnreader-sources/issues/314)
=> New source NovelTop1 added

strings/languages/fr/strings.json
Some small hesitations on how to translate :
- "Offset" is difficult to translate with this context
- "Badges" For me, it's "a small piece of metal, plastic, or cloth bearing a design or words, typically worn to identify a person or to indicate membership of an organization or support for a cause." (I know it can be virtual but I'm not sure I have the context of the application but it is a transparent word according to this definition)
- "grid" translated into "grille" is a bit weird
- Should I translate "Novel" by its translation ("roman") ?
- "Scroll" is very well known and more used than the word "défilement" but I don't know if you want a translation with only French words (I left "scroll" here)
=> add french translation

src/screens/history/HistoryScreen.tsx, src/screens/updates/UpdatesScreen.tsx, src/sources/en/ranobes.js, src/sources/ru/ranobes.js, src/sources/sourceManager.ts, src/sources/sources.json, src/utils/constants/dateFormats.ts, strings/languages/en/strings.json, strings/translations.ts, strings/types/index.ts
fixed source ranobes.net (Closes LNReader/lnreader-sources#70)
added ranobes.com source
added new lines for translation
=> Source Updates

src/services/backup/v1/backup.js, src/sources/multisrc/madara/MadaraGenerator.ts, src/sources/multisrc/madara/MadaraSources.json, src/sources/sourceManager.ts, src/sources/sources.json
Added following sources 
Zetro Translation, 
Nocturne, 
Asada Translation, 
Sugar Babies.
Closes LNReader/lnreader-sources#312 
Closes LNReader/lnreader-sources#307
Closes LNReader/lnreader-sources#301
Closes LNReader/lnreader-sources#291
=> Added following sources Zetro, Nocturne, Asada and SugarBB

src/screens/updates/UpdatesScreen.tsx, src/sources/en/ranobes.js, src/sources/helpers/constants.js, src/sources/ru/ficbook.js, src/sources/ru/jaomix.js, src/sources/ru/ranobes.js, src/sources/ru/rulate.js, src/sources/sourceManager.ts, src/sources/sources.json
=> Ficbook New Source

src/sources/ru/authortoday.js, src/sources/ru/ficbook.js, src/sources/ru/ranobehub.js, src/sources/ru/rulate.js, src/sources/sourceManager.ts, src/sources/sources.json
=> add AuthorToday

package-lock.json, package.json
=> Revert "chore(deps): bump react-native-reanimated from 2.2.4 to 2.10.0"

src/sources/en/ranobes.js
LNReader/lnreader-sources#429 Closes
=> fix ranobes

src/screens/reader/components/ChapterDrawer.js
@rajarsheechatterjee 
First of all I really like your redesign, however you forgot to theme the text color, so it was barely readable in darkmode
=> chapter drawer themed textcolor

src/navigators/BottomNavigator.js
A fix for some dark themes:
- Before
- After
=> fixed library button color

src/sources/ru/jaomix.js, src/sources/ru/ranobelib.js
Fixing chapter parsing in the source jaomix.ru
=> fix Jaomix

src/sources/multisrc/wpmangastream/WPMangaStreamScraper.js
I can't delete commits.
I ded.
=> fix: images on noblemtl

src/sources/en/ranobes.js, src/sources/multisrc/wpmangastream/WPMangaStreamScraper.js
Yes
Also fixes https://github.com/LNReader/lnreader-sources/issues/444#issue-1561380824
=> Fix: Author and Status for WPMangaStreamScraper

src/sources/id/sakuranovel.js, src/sources/multisrc/wpmangastream/WPMangaStreamScraper.js
fixes https://github.com/LNReader/lnreader-sources/issues/456#issue-1593031462
images don't appear consistently, but I think that's more on the source's side.
=> fix: Sakuranovel

src/sources/en/pawread.js, src/sources/id/sakuranovel.js, src/sources/multisrc/wpmangastream/WPMangaStreamScraper.js, src/sources/sourceManager.ts, src/sources/sources.json
for https://github.com/LNReader/lnreader-sources/issues/439
also some other minor adjustments
=> feat(Add Source): Pawread

src/redux/settings/settings.reducer.js, src/screens/reader/components/WebViewReader.tsx, src/screens/settings/SettingsReaderScreen/SettingsReaderScreen.tsx
Reused components from custom CSS feature and added script tag to WebView reader.
=> feat: Add custom Javascript (Closes #572)

src/components/Counter/Counter.tsx, src/components/PlusMinusField/PlusMinusField.tsx, src/screens/browse/components/SourceCard/SourceCard.tsx, src/screens/reader/components/ReaderBottomSheet/ReaderLineHeight.tsx, src/screens/reader/components/WebViewReader.tsx, src/screens/settings/SettingsReaderScreen/Modals/CustomFileModal.tsx, src/screens/settings/SettingsReaderScreen/Modals/FontPickerModal.tsx, src/screens/settings/SettingsReaderScreen/ReaderTextSize.tsx, src/screens/settings/SettingsReaderScreen/Settings/CustomCSSSettings.tsx, src/screens/settings/SettingsReaderScreen/Settings/CustomJSSettings.tsx, src/screens/settings/SettingsReaderScreen/Settings/DisplaySettings.tsx, src/screens/settings/SettingsReaderScreen/Settings/GeneralSettings.tsx, src/screens/settings/SettingsReaderScreen/Settings/ReaderThemeSettings.tsx, src/screens/settings/SettingsReaderScreen/SettingsReaderScreen.tsx, strings/languages/en/strings.json, strings/types/index.ts
- added sourceID to WebViewReader in body as id for source specific css configuration
- added document picker for CSS and JS files
- added Modal for Custom CSS and Custom JS
- added sourceID to browse screen for users to be able to create custom css
=> better css v2

src/screens/reader/components/WebViewReader.tsx, src/screens/settings/SettingsReaderScreen/Modals/CustomFileModal.tsx, src/screens/settings/SettingsReaderScreen/Settings/CustomJSSettings.tsx, src/screens/settings/SettingsReaderScreen/SettingsReaderScreen.tsx, strings/languages/en/strings.json, strings/types/index.ts
Giving users the possibility to access the variables html, novelName, chapterName, sourceId, chapterId and novelId, when they are creating a customJS
=> Access to variables for customJS

src/database/queries/NovelQueries.js, src/screens/library/LibraryScreen.tsx, src/screens/novel/components/NovelScreenButtonGroup/NovelScreenButtonGroup.tsx, src/screens/novel/components/SetCategoriesModal.tsx
Through a long press the novel can now directly be added to a category in the library, even if it wasn't before.
This should finish #611
=> directly add novel to library category

src/sources/ch/linovelib.js
Should also fix the `fetchApi` unrefined error
=> refactor(source): Use fetchHtml for Linovelib

src/sources/kr/Agitoon.js, src/sources/multisrc/wqmangastream/WQMangaStreamScraper.js
Updates for Kolnovel chapter scraping and Agitoon popularNovels screen
=> Fix: Update Kolnovel & Agitoon

src/sources/multisrc/readwn/ReadwnGenerator.js, src/sources/sources.json
Readwn URL is updated to www.wuxiap.com
=> Update Readwn URL

android/app/src/main/assets/js/index.js
=> Using classes for reader UI

src/sources/en/fastnovel.js, src/sources/en/novelupdates.js, src/sources/multisrc/madara/MadaraGenerator.ts, src/sources/multisrc/madara/MadaraScraper.js, src/sources/multisrc/madara/MadaraSources.json
for inoveltranslations source for when the notes field isn't used for the novel in question
=> fix(source): Novel Updates, FastNovel & Arnovel

src/plugins/pluginManager.ts, src/plugins/types/index.ts, src/screens/WebviewScreen/WebviewScreen.tsx, src/utils/fetch/fetch.ts
corresponding update for https://github.com/LNReader/lnreader-sources/pull/631
- Updating User Agent for specific plugin is possible. just need an UI Component
=> Classes for Plugins

src/sources/en/NovelOnline.ts
https://github.com/LNReader/lnreader-sources/issues/638
=> Updated NovelOnline.ts

src/sources/en/novelupdates.js, src/sources/es/esmtlnovel.js, src/sources/sourceManager.ts, src/sources/sources.json
From @WilsonGabrielMinayaGuzman
Source tested by me
Also addresses https://github.com/LNReader/lnreader-sources/issues/682
=> add(source) MTLNovel (ES)

CONTRIBUTING.md
Build fails on latest python 3.12, use 3.11 or below
=> Update CONTRIBUTING.md python

COMMON_ERRORS.md, CONTRIBUTING.md
just added a few things to help possible contributors get acquainted with the project easier
=> Contributing markdown file update

src/plugins/pluginManager.ts
with https://github.com/LNReader/lnreader-sources/pull/724
=> update plugins host

src/database/db.ts, src/database/tables/CategoryTable.ts, src/database/tables/ChapterTable.ts, src/database/tables/NovelTable.ts, src/services/updates/LibraryUpdateQueries.ts
- fix: default category is added after id = 1 was deleted
- add page fields
=> Pre alpha patch 5

src/services/updates/LibraryUpdateQueries.ts
We can use where statement.
https://www.sqlite.org/lang_upsert.html
=> Fix update only when chapter info changed

src/sources/en/readlightnovel.ts, src/sources/multisrc/ifreedom/IfreedomScraper.js, src/sources/multisrc/rulate/RulateScraper.js, src/sources/ru/bookriver.js, src/sources/ru/freedlit.ts, src/sources/ru/jaomix.js
fixes readlightnovel source (closes https://github.com/LNReader/lnreader-sources/issues/763)
fix dates for Russian sources
=>  fix readlightnovel

android/app/src/main/java/com/rajarsheechatterjee/EpubUtil/EpubUtil.java, android/app/src/main/java/com/rajarsheechatterjee/EpubUtil/EpubUtilPackage.java, android/app/src/main/java/com/rajarsheechatterjee/LNReader/MainApplication.java, android/app/src/main/java/com/rajarsheechatterjee/NavigationBarColor/NavigationBarColorModule.java, src/hooks/persisted/useNovel.ts, src/native/EpubUtil.ts, src/services/epub/import.ts
- Reduce time complexity O(n^2*k) -> O(nlogn), memories consuming
=> cheaper epub parsing

android/app/src/main/assets/css/index.css, android/app/src/main/assets/js/index.js, android/app/src/main/assets/js/text-vibe.js, src/database/queries/LibraryQueries.ts, src/hooks/persisted/useSettings.ts, src/screens/reader/components/ReaderBottomSheet/ReaderBottomSheet.tsx, src/screens/reader/components/WebViewReader.tsx, src/screens/settings/SettingsReaderScreen/Settings/GeneralSettings.tsx, src/screens/settings/SettingsReaderScreen/SettingsReaderScreen.tsx, src/services/epub/import.ts, src/services/updates/LibraryUpdateQueries.ts, src/services/updates/index.ts
- wrong chapter position after updating
- reader footer styles
- reader swipe gestures sensitive
- horizontal scrollbar
- bionic reading
=> Fix bugs & Reader improvement

package-lock.json, package.json, src/hooks/persisted/usePlugins.ts, src/plugins/pluginManager.ts, src/plugins/types/index.ts, src/screens/browse/BrowseSettings.tsx, src/screens/browse/components/BrowseTabs.tsx, src/utils/constants/languages.ts
- add htmparser2
- flatten plugins list
- repo version
=> Update plugin sanbox

src/utils/constants/languages.ts
- Left-to-Right for arabic language with u200e
- Fix alpabethic order
=> Fix arabic alignment and language list order

android/app/src/main/assets/css/index.css, android/app/src/main/assets/js/index.js, android/app/src/main/assets/js/type.d.ts, src/hooks/persisted/useSettings.ts, src/screens/reader/ReaderScreen.tsx, src/screens/reader/components/WebViewReader.tsx, src/screens/settings/SettingsReaderScreen/Modals/VoicePickerModal.tsx, src/screens/settings/SettingsReaderScreen/Settings/TextToSpeechSettings.tsx, src/screens/settings/SettingsReaderScreen/SettingsReaderScreen.tsx
- Speak by paragraph(closes https://github.com/LNReader/lnreader/issues/1041)
- Select available voice in device
=> enhance TTS

strings/languages/fr_FR/strings.json, strings/translations.ts
Update translation resources for the fr_FR/string.json file.
Translation of part of the resources into French. (There are still resources left to translate)
Possibility to have the application in French
=> Adding support for French localization

src/database/tables/RepositoryTable.ts
goes with https://github.com/LNReader/lnreader-plugins/pull/945
=> version increase for sources (arabic \u200e)

src/components/SearchbarV2/SearchbarV2.tsx, src/screens/library/LibraryScreen.tsx, strings/languages/en/strings.json, strings/types/index.ts
Missed this functionality from Mihon for when i'm indecisive
https://youtu.be/POQg-Du9dS8
note: This is my first time using react or react-native so the code may have issues
Also moves the import epub button into a dropdown with the open random button to avoid having too many buttons in top bar
=> Add open random entry button

App.tsx, android/app/src/main/java/com/rajarsheechatterjee/FileManager/FileManager.kt, src/hooks/persisted/usePlugins.ts, src/native/FileManager.ts, src/plugins/pluginManager.ts, src/screens/GlobalSearchScreen/hooks/useGlobalSearch.ts, src/screens/reader/ReaderScreen.tsx, src/services/backup/legacy/index.ts, src/services/backup/utils.ts, src/services/epub/import.ts
- synchronize readFile
- lazy initialization for plugin
- move plugins separate folder
=> Lazy init for plugin

android/app/src/main/java/com/rajarsheechatterjee/EpubUtil/ChapterEntry.kt, android/app/src/main/java/com/rajarsheechatterjee/EpubUtil/EpubUtil.kt
- Merge chapter pages into one chapter
<p float="left" align="top">
Instead of
</p>
- scan cover in Images folder
- Fix: ignore non-existed files (closes #1109)
=> Merge epub chapters

src/plugins/helpers/constants.ts
it took me 3 years to make this PR please merge
=> Fix: update defaultCover URL

src/screens/BrowseSourceScreen/components/FilterBottomSheet.tsx
- displays labels instead of values
=> Fix: Filters

src/sources/en/freewebnovel.ts, src/sources/en/lightnovelpub.js, src/sources/en/novelupdates.js, src/sources/id/sakuranovel.js
Fixes:
Freewebnovel > Libread
https://github.com/LNReader/lnreader-sources/issues/708
https://github.com/LNReader/lnreader-sources/issues/668
https://github.com/LNReader/lnreader-sources/issues/664
https://github.com/LNReader/lnreader-sources/issues/661
Novel Updates Cover after Login (?)
=> (src fix) Maintainance

android/app/src/main/assets/css/index.css, android/app/src/main/assets/js/core.js, android/app/src/main/assets/js/index.js, android/app/src/main/java/com/rajarsheechatterjee/EpubUtil/EpubUtil.kt, src/hooks/persisted/useSettings.ts
- fix tts dfs algorithm
- fix reader webview padding
- close https://github.com/LNReader/lnreader/issues/1206
- fix throw Exception toc not found
=> Fix reader bugs

src/screens/browse/components/BrowseTabs.tsx
Sorts the source/plugin list by its name, requested by #1200
=> Enhancement: Sort source list by its name

scripts/setEnvFile.cjs, src/hooks/persisted/usePlugins.ts, src/screens/browse/components/BrowseTabs.tsx
when the app is in dev mode you can "update" plugins infinitely, for testing purposes
---
re fix setEnvFile.cjs 043221b (related #1130)
=> infinit plugin update if in dev mode

src/screens/novel/components/EditInfoModal.tsx
Fix for #1231, info was not saving because wrong params was passed to the function, SQL transaction did not proceed.
[novelInfo.webm](https://github.com/user-attachments/assets/26cb859b-fb10-48e9-bb93-38e9c91454d8)
=> Fix novel info not saving

scripts/setEnvFile.cjs
=> setEnvFile: fix error when no .env file

src/screens/novel/components/NovelAppbar.tsx
Closes #1341 
| v2.0.0-beta.3 | this pr |
| - | - |
| ![Animation2-ezgif com-optimize](https://github.com/user-attachments/assets/e0eac143-13fd-416f-ae44-0e543d487b72) | ![Animation-ezgif com-optimize](https://github.com/user-attachments/assets/42b36747-2045-440e-a712-f242684ddca1) |
=> fix: "Edit cover" function is not called

src/services/ServiceManager.ts
=> Fix service manager down

src/services/backup/legacy/index.ts
When you try to create a backup file on Android 11+ device you get this error  /storage/emulated/0/h/inreader_backup_YYYY-MM-DD_HH_mm.json: open failed: EPERM (Operation not permitted)
I tried the modifications on my device "android 14" and it works successfully.
=> fix : ERROR $ open failed: EPERM (Operation not permitted)

src/hooks/persisted/useDownload.ts, src/screens/novel/NovelScreen.tsx, src/services/ServiceManager.ts
closes #1383
- Fixes the chapter download notification stuf on "Prepairing"
- Fixes the download spinner not showing in chapter list
=> Fix some bugs with task queue

src/screens/novel/NovelScreen.tsx, src/screens/novel/components/Info/NovelInfoComponents.tsx, src/screens/novel/components/Info/NovelInfoHeader.tsx, src/screens/novel/components/NovelScreenList.tsx, strings/languages/en/strings.json, strings/types/index.ts
Addresses #1454 
Added save novel cover button
Let me know if i should add it in the NovelAppBar as well since Edit cover option is also present over there
=> feat: Save novel cover (#1454)

package-lock.json, package.json, src/hooks/persisted/useImport.ts, src/screens/Categories/CategoriesScreen.tsx, src/screens/Categories/components/AddCategoryModal.tsx, src/screens/library/LibraryScreen.tsx, src/screens/library/components/LibraryListView.tsx, src/screens/library/hooks/useLibrary.ts
=> fix: categories and update library on novel import

shared/Epub.cpp, src/services/epub/import.ts
- unsafe path
- absolute path mapping for label
=> fix: epub parsing
