LNReader/lnreader

src/sources/jp/syosetu.js
Changed oneshot chapter names to "Oneshot" to avoid too long chapters names destroying UI.
=> fix(syosetu): change oneshot chapter name

src/sources/en/fastnovel.js
In Fastnovel the `nextChapter` is undefined in last chapter of any novel and using `replace` on `nextChapter` leads to crash.
=> fix(source): nextChapter link undefined

src/hooks/reduxHooks.js
Fixes a bug where the app would crash if all the chapters in a novel were read, and the user tried to open it.
Video of before and after applying the change
https://user-images.githubusercontent.com/13577339/161591854-4d0fe1a7-2293-4d3b-8613-e412a2278c2e.mp4
(If the above video doesn't work) https://youtu.be/MoH2Gd7OAGY
=> Fixed Last Read Crash

src/screens/reader/ReaderScreen.js
Because of last-minute name changes to the functions I forgot to change the name of `setWebViewStartScroll` to `setWebViewScroll` when it was called in `scrollToSavedProgress` and it was causing the app to crash
=> fix(typo): spelling mistake causing a crash

src/sources/jp/syosetu.js
Change syosetsu's cover to not available to be more in-sync with other sources instead of using custom one
=> fix(syosetu): Change cover to unavailable

android/app/src/main/AndroidManifest.xml
Add to AndroidManifest.xml a clause about querying TTS to remove `Unresolved Promise: No TTS Engine Installed` error in Android 11 Phones.
=> fix(tts): Android11 Manifest TTS Support

src/sources/en/novelupdates.js
Before the genres would be split on every space so genres like "Slice of Life" would become "Slice" "Of" "Life"
This would cause react error on every novel with both
"School Life" and "Slice of Life" genres because it would cause duplicate key for genre "Life"
=> fix(source): Fix NovelUpdates genres

android/app/build.gradle
Instead of just leaving it at 1, this PR implements an automatically incremented (based on the version number) version code.
This implementation supports pretty high version codes, so that should be no issue.
Since the version code is used to differentiate versions in android programmatically, this should allow things like including the app in F-Droid repositories.
=> Generate versionCode

src/database/queries/ChapterQueries.ts, src/redux/novel/novel.actions.js
Make deleting chapters do 5 coccurent deletion at a time, thus removing the `Excessive number of pending callbacks` warn.
=> fix(delete_chapter): Excessive number of pending callbacks warn

src/hooks/useTextToSpeech.js, src/screens/reader/ReaderScreen.js, src/screens/reader/components/ReaderAppbar.js
Also this feature uses paragraphs as breakpoints.
=> simply tts to prevent it freezes the app

src/screens/reader/ReaderScreen.js, src/screens/reader/components/ReaderFooter.js, src/screens/reader/components/ReaderSeekBar.js, src/screens/reader/components/TextReader.tsx, src/screens/reader/components/WebViewReader.tsx
slider inside Seekbar component
=> fix slider displays uncorrectly, rearrange seekbar props

android/app/src/main/java/com/rajarsheechatterjee/LNReader/MainActivity.java, android/app/src/main/java/com/rajarsheechatterjee/VolumeButtonListener/VolumeButtonListener.java, src/redux/settings/settings.reducer.js, src/screens/reader/ReaderScreen.js, src/screens/reader/components/ReaderBottomSheet/ReaderBottomSheet.tsx, src/screens/settings/SettingsReaderScreen/SettingsReaderScreen.tsx, strings/languages/en/strings.json, strings/types/index.ts
Added volume button scroll amount
=> extending Volume button feature, by scroll amount

src/sources/multisrc/readwn/ReadwnScraper.js
I noticed several old ReadWN related bug reports of chapters not loading that were hard to reproduce.
I found one I was able to reproduce.
I traced the issue down to the fact all the chapterUrls are actually generated procedurally in our script (1..2..3..), but sometimes authors use different naming schemes (001...002...003).
This is janky. So, to fix this, I made it more janky.
Based on my observations on ReadWN, the first hundred chapters comfortably display by default, In probably 90% of usecases, the issue will be ironed out by chapter 100. So I have as many chapters as it can generate according to the table of contents, and then resume procedural generation from where it left off until the latest chapter of the novel.
In the test case I had, this fixed the issue perfectly.
I tested …
=> fix(ReadWN): Implemented better chapter assumption

src/screens/reader/ReaderScreen.js
Fixes #593 
This delays the scroll call just enough that it correctly works with downloaded chapters.
https://github.com/LNReader/lnreader/assets/5789439/1a1d3eb1-558e-42fc-9890-fb8836facde3
=> Fix scroll to progress on downloaded chapters

src/sources/en/novelupdates.js, src/utils/fetch/fetch.ts
1. Adjusted UA string to my UA string on my Pixel5A running Android 13. User Agents have become more obscured and generic, so having a very specific UA string will start to stand out.
2. Implemented the capacity to specify a unique user agent string, or remove it entirely. Now done by switching line order and adding comments.
Why, you ask, would I want to remove a user agent string? Because if there's no UA string you can get the page without lazy loading images, which can potentially make or break pulling images. Sure, I can just use a raw fetch, but that doesn't have cloudflare bypass. (Specifically for ReaperScans)
This is the best of both worlds, while still functioning as expected with existing scripts.
Theoretically fixes https://github.com/LNReader/lnreader-sources/issues/473 but …
=> fix(fetch): Add capacity to change UA string

src/sources/fr/noveldeglace.js
addresses the following issues:
https://github.com/LNReader/lnreader-sources/issues/434
https://github.com/LNReader/lnreader-sources/issues/416
for some reason, the server returns a wrong packet header of the gzip, but only on the first request (afterward it's fine when the chapter is cached)
=> fix(source): NovelDeGlace (FR)

src/sources/en/lightnovelpub.js, src/sources/en/novelhall.js, src/sources/en/novelupdates.js, src/sources/en/pawread.js, src/sources/id/indowebnovel.js, src/sources/id/sakuranovel.js, src/sources/kr/Agitoon.js, src/sources/multisrc/madara/MadaraGenerator.ts, src/sources/multisrc/madara/MadaraScraper.js, src/sources/multisrc/madara/MadaraSources.json
to fix https://github.com/LNReader/lnreader-sources/issues/525
points to correct url separator
- add update to source url
1stkissnovel.love -> 1stkissnovel.org
- Fix spacing in Agitoon
- Remove pawread text in chapters
=> fix(Source): Arnovel

src/sources/ch/linovelib.js, src/sources/sourceManager.ts, src/sources/sources.json
Adding [Linovelib](https://w.linovelib.com/) as a source.
```json
{
"sourceId": 165,
"sourceName": "Linovelib",
"url": "https://w.linovelib.com",
"lang": "Chinese",
"icon": "https://w.linovelib.com/images/logo.png"
}
```
Caveat: I couldn't get search working as it seems there are some kind of challenge blocking the initial load. Maybe someone can take a look at it.
Closes: https://github.com/LNReader/lnreader-sources/issues/104
=> feat(source): Add Linovelib

src/sources/ch/linovelib.js
Didn't realize that the naming convention was different from the source repo.
Hopefully this should fix the plugin.
=> fix(source): fix incorrect property name

src/sources/ch/linovelib.js
The original images are locked behind a CDN that has a challenge check.
This patch will bypass it
=> fix(source): bypass image CDN in Linovelib

babel.config.js, package-lock.json, package.json, src/database/queries/ChapterQueries.ts, src/hooks/githubUpdateChecker.ts, src/navigators/Main.tsx, src/navigators/types/index.ts, src/screens/BrowseSourceScreen/BrowseSourceScreen.tsx, src/screens/WebviewScreen/WebviewScreen.tsx, src/screens/browse/components/PluginCard.tsx, src/screens/browse/components/PluginMenu.tsx, src/screens/reader/ReaderScreen.js, src/screens/reader/ReaderScreen.tsx, src/screens/reader/components/ChapterDrawer.js, src/screens/reader/components/ReaderSeekBar.js, src/screens/reader/components/WebViewReader.tsx, tsconfig.json
- Fix: When try opening chapters from Update or History screen, reader (with full of images) gave wrong value of document height to app (1100 instead of 8100).
The small one is height of content without rendered images. So I think somehow images were lazy load for these screens.
-> update minscroll pararelly with postion. 
- TypeScript: Because of old Drawer Navigation is quite mess, it's not Stack Screen nor Drawer Screen. It's both :( 
So I replaced by DrawerLayoutAndroid (very same).
- Current theme is conflicting with NavigationContainer. only 2 attributes matched.
- Fetch ChapterText, prev, next chapter at the same time. Because `nextChapter` coming up later which make whole reader re-render. Looks kinda bad. I will add index for chapter and maybe also download, so time is not a big …
=> Fix: wrong mincroll in Update, History. TS Reader, Navigation (Main)

src/sources/en/novelupdates.js
cloudflare requires the same cf_clearance cookie + ip address + user-agent as the webview
novelupdates.js was using the wrong user-agent which caused errors when novelupdates had cloudflare turned on and when the app navigated to a website using cloudflare (ex. foxaholic)
fixes https://github.com/LNReader/lnreader-sources/issues/669 and https://github.com/LNReader/lnreader/issues/818
=> fix cloudflare on novelupdates

package-lock.json, src/redux/settings/settings.reducer.js, src/screens/reader/ReaderScreen.js, src/screens/reader/components/ReaderBottomSheet/ReaderBottomSheet.tsx, src/screens/reader/components/ReaderSeekBar.tsx, src/screens/reader/components/WebViewReader.tsx, src/screens/reader/components/functionStrings/horizontalReaderPages.ts, src/screens/reader/components/stringCreators/createStyle.ts, src/screens/reader/components/stringCreators/createSwipeGestures.ts, src/screens/reader/components/stringCreators/horizontalReaderPages.ts, src/screens/settings/SettingsReaderScreen/Settings/GeneralSettings.tsx, strings/languages/en/strings.json, strings/types/index.ts
working:
- Swapping back and forth through pages
- displaying next chapter button on the last page
- Resume progress
not working:
- Resume progress after switching reading mode
https://github.com/LNReader/lnreader/assets/69157453/674d0c0c-ebf1-41b1-b22d-f99dcaaf1a67
=> Reader Pageination

src/services/updates/updates.js
bug: when the last novel in the library gives an error (ex. cloudflare) then the app will be unable to start another library update until u force stop the app
1. moved resolve and schedule notif after the for loop
2. removed the if isrunning inside the try since the for loop already checks for it
=> fix updating library freeze

.github/workflows/build.yml, .github/workflows/lint.yml, src/hooks/persisted/useNovel.ts, src/plugins/pluginManager.ts, src/services/backup/drive/index.ts, src/services/backup/remote/index.ts, src/services/epub/import.ts, src/services/updates/LibraryUpdateQueries.ts, strings/languages/en/strings.json, strings/languages/zh_CN/strings.json, strings/types/index.ts
should use upsert.
also rename the workflows, and add more translations.
=> Fix chapters status lost problem

src/database/queries/ChapterQueries.ts, src/database/queries/NovelQueries.ts, src/screens/BrowseSourceScreen/useBrowseSource.ts, src/screens/browse/migration/MigrationNovelList.tsx, src/screens/library/LibraryScreen.tsx, src/screens/reader/ReaderScreen.tsx, src/services/backup/legacy/index.ts, src/services/migrate/migrateNovel.ts, src/services/plugin/fetch.ts
- Make the tab width fit to the tab content (like Tachiyomi). 
- fix legacy backup
=> Fix tabiew

src/database/queries/ChapterQueries.ts, src/database/queries/NovelQueries.ts, src/screens/novel/NovelScreen.tsx, src/services/epub/import.ts, src/services/updates/LibraryUpdateQueries.ts
- insertId possibly is -1
- downloadNewChapter logic
- novelDir does not exist
- fix: update novel/chapter metadata logic
=> Fix: insert/update novel/chapter logic

.github/workflows/build.yml, android/app/build.gradle, android/app/src/main/AndroidManifest.xml, env.d.ts, package-lock.json, package.json, scripts/setEnvFile.cjs, src/hooks/common/githubUpdateChecker.ts, src/screens/more/About.tsx, src/services/backup/utils.ts, src/utils/versionUtils.ts
GitHub action: bd2a360 
- custom apk:
- packet name with git commit id
- app name with git commit id
- cached `npm install`
- update actions versions
---
About page: 1635725
- Version based on package.json
- added git commit hash to the version if not Stable
- RELEASE_DATE, GIT_HASH, BUILD_TYPE created at build time from setEnvFile.cjs
- special BUILD_TYPE for github actions
- Version modal copy on click
- removed versionUtils
=> About page Version update & GH action update

android/app/src/main/java/com/rajarsheechatterjee/FileManager/FileManager.kt, src/database/queries/ChapterQueries.ts, src/database/queries/NovelQueries.ts, src/native/FileManager.ts, src/plugins/helpers/fetch.ts, src/plugins/pluginManager.ts, src/plugins/types/index.ts, src/screens/reader/components/WebViewReader.tsx, src/services/plugin/fetch.ts, src/services/updates/LibraryUpdateQueries.ts
- before: call fetch from React -> native Android make okhttp3 request -> return response package to React -> React decode base64 -> React send base64 to native Android -> write base64 to file :)))
- now: call downloadFile -> write bytestream to file 
- now support only text file
=> Download file with cookie persisted from RN

src/screens/reader/ReaderScreen.tsx
Progressbar kept being displayed after opening the chapterDrawer if it was opened through the ReaderFooter
=> fix: hide progressbar

src/screens/reader/ReaderScreen.tsx
the scrolling by volume button right now scrolls 100% of the screen, which hides text when scrolled so, the commit is just changing the the scrolling to 50%.
=> Volume scrolling fix

android/app/src/main/assets/css/index.css
From 16px to 14px.
It's better looking.
Current:
Modified(commit):
Stable 1.1.19:
=> Decrease reader progress bar font-size

android/app/src/main/assets/css/index.css
Since the tts buttons has been replaced by the bubble version, it's now possible.
Proportions taken based on Stable 1.1.19 except vertical (shorter than stable, longer than current beta)
If you want to make vertical like stable the height values is around 55vh
Current:
Modified (commit):
=> Progress bar - better proportions

src/screens/browse/components/BrowseTabs.tsx
Make swiping source/plugins less sensitive, related issue #1199 
https://github.com/user-attachments/assets/de4136f1-1b25-4f5f-b869-43b1befae593
=> Enhancement: Make swiping of plugins/sources less sensitive

src/screens/browse/components/BrowseTabs.tsx
Feedback from other users seems to be that the swiping offset is too aggressive, making swiping left and right too janky.
Lowered the value from 62 to 30, triggering the swipe would be happen more frequently when scrolling, but swiping left and right would be much smoother.
=> Update swiping offset to be less aggressive

android/app/src/main/assets/css/index.css
After VanJS commit it was disabled by mistake.
=> Re-disable user-select on next-button and info-text

src/database/queries/ChapterQueries.ts
had issue on novelupdates where opening novels for the first time will give cant parse page error since sql has wrong syntax
=> fix 'cant parse page' sql syntax error

src/screens/BrowseSourceScreen/components/FilterBottomSheet.tsx
=> Add FilterTypes.Switch and FilterTypes.TextInput support to plugin filters

src/components/NovelCover.tsx
Fixes covers showing like this in the case screen width changes 
https://youtu.be/Sc3Jl0aRXlg
=> Fix cover height incorrect when screen width changes

src/hooks/persisted/usePlugins.ts, src/plugins/types/index.ts, src/screens/browse/components/BrowseTabs.tsx, src/screens/browse/components/Modals/SourceSettings.tsx, strings/languages/en/strings.json
Adds settings to plugins. issue: #1264 
It allows the user to configure the plugins. For example the plugin I'm working on for komga.
The plugin defines the settings in the following format:
`
pluginSettings = {
email: {
value: "",
label: "Email"
},
password: {
value: "",
label: "Password"
},
url: {
value: "",
label: "URL"
}
}
`
And the app then adds a cog in the installed plugin like this:
When pressed a modal opens up with the inputs defined in the plugin:
The setting are stored in the plugin storage. An can be accessed by the plugins.
Corrently it only allows text inputs. Maybe in the future other types could be added. 
Everything seems to be working but I'm sure there will be problems with this as I'm not very familiar with react. Just point them out, maybe answer a few dumb questions …
=> Allow user input for plugins configurations

src/hooks/common/useFullscreenMode.ts
Makes it more transparent in the reader mode.
Before commit:
After commit modifications:
=> More transparent android nav bar

src/components/ListView.tsx, src/components/NovelCover.tsx, src/navigators/BottomNavigator.tsx, src/navigators/Main.tsx, src/navigators/types/index.ts, src/screens/browse/BrowseScreen.tsx, src/screens/history/HistoryScreen.tsx, src/screens/library/LibraryScreen.tsx, src/screens/more/MoreScreen.tsx, src/screens/novel/components/LoadingAnimation/NovelScreenLoading.tsx, src/screens/updates/UpdatesScreen.tsx
All changes match mihon functionality
=> Better bottom navigation

src/screens/novel/components/EditInfoModal.tsx
Closes #1356 
| v2.0.0-beta.3 | this pr |
| - | - |
| ![Image 2024-12-16](https://github.com/user-attachments/assets/91811b70-21ee-4119-a155-987bbac03ebf) | ![Image 2024-12-16](https://github.com/user-attachments/assets/6a0daa20-7f2f-4006-8b0d-361aacbc7c17) |
**Note:** Also fixed a small bug where empty tags could be added when the novel already had at least one valid tag, similar to what happens in the first image.
=> fix: "Add tag" input does not work correctly

src/services/backup/legacy/index.ts
in android file system you can't use the char  ' : '  so lnreader file name:
"Inreader_backup_YYYY-MM-DD_HH:mm.json"
you can't write it as a file. 
so i edit it to looks like
"Inreader_backup_YYYY-MM-DD_HH_mm.json"
=> CREATE BACKUP FILE NOT WORKING, FIXED

src/screens/library/LibraryScreen.tsx, src/screens/library/components/LibraryListView.tsx, src/screens/more/TaskQueueScreen.tsx, src/screens/updates/UpdatesScreen.tsx, src/services/ServiceManager.ts, src/services/backup/drive/index.ts, src/services/backup/selfhost/index.ts, src/services/download/downloadChapter.ts, src/services/epub/import.ts, src/services/migrate/migrateNovel.ts, src/services/updates/index.ts
=> Improve Task Queue

src/screens/reader/ReaderScreen.tsx, src/screens/reader/components/ReaderAppbar.tsx, src/screens/reader/hooks/useChapter.ts
Previously, the bookmark button in the reader top bar would always reset to whatever the status was when you first opened the chapter. Additionally, if you read part of a chapter or bookmarked a chapter, left reader mode, then pressed the "continue reading" button to get back to where you left off, the bookmark status and reading progress would not have been saved like if you opened the chapter via the list.
I tried to make the least intrusive changes I could, since the core problem with the "continue reading" bug is that state variables are not updated, and instead changes are directly saved to the database in other sections. The best solution would require rewriting a good section of the codebase.
If changes are necessary, please let me know.
=> Fixed last read not updating and bookmark button in reader mode.

src/screens/novel/components/Info/NovelInfoComponents.tsx
Save and edit buttons for novel cover image were misaligned while resolving conflicts
Before:
After:
=> fix: fix alignment of save novel cover button
